[workspace]
members = [
  "crates/nanocl_models",
  "crates/nanocl_client",
  "bin/nanocld",
  "bin/nanocl"
]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[patch.crates-io]
nanocl_models = { path = "crates/nanocl_models" }
nanocl_client = { path = "crates/nanocl_client" }
