[workspace]
members = [
  "nanocl-models",
  "nanocl-client",
  "nanocld",
  "nanocl"
]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[patch.crates-io]
nanocl-models = { path = "nanocl-models" }
nanocl-client = { path = "nanocl-client" }
bollard = { git = "https://github.com/leon3s/bollard" }
