[workspace]
members = [
  "crates/nanocl-models",
  "crates/nanocl-client",
  "bin/nanocld",
  "bin/nanocl"
]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[patch.crates-io]
nanocl-models = { path = "crates/nanocl-models" }
nanocl-client = { path = "crates/nanocl-client" }
