[package]
name = "nanocl_stubs"
version = "0.0.11"
edition = "2021"
authors = ["nanocl contributors <team@next-hat.com>"]
description = "Nanocl shared data model"
readme = "readme.md"
license = "MIT OR Apache-2.0"
homepage = "https://docs.next-hat.com/docs/guides/nanocl/overview"
repository = "https://github.com/nxthat/nanocl"

[lib]
bench = false

[features]
utoipa = ["dep:utoipa"]
serde = ["dep:serde", "uuid/serde", "chrono/serde"]

[dependencies]
bollard-next = { version = "0.14.1" }
uuid = { version = "1.2.2" }
serde = { version = "1.0.152", features = ["derive"], optional = true }
serde_json = "1.0.91"
chrono = "0.4.23"
# Dependency required with dev feature
utoipa = { version = "3.0.2", features = ["uuid", "chrono"], optional = true }
